name: build and testing
on: [push]
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
        env:
          VOLC_ACCESSKEY: ${{ secrets.VOLC_ACCESSKEY }}
          VOLC_SECRETKEY: ${{ secrets.VOLC_SECRETKEY }}
